[features]
seeds = false
skip-lint = false
[programs.devnet]
custom_message = "HGUDvDr2Ya4hhHr45NZULdgq2EKBwCD6FyEuYh4EacsM"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/creators_choice/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
